DROP DATABASE IF EXISTS COMPTA; 
CREATE DATABASE IF NOT EXISTS COMPTA;

USE COMPTA;

DROP DATABASE IF EXISTS ARTICLE;
CREATE DATABASE IF NOT EXISTS ARTCICLE (
    id INT(11) PRIMARY KEY,
    ref VARCHAR(50),
    designation VARCHAR(50)
    prix DECIMAL (7,2)
    id_fou INT(11)
);



DROP DATABASE IF EXISTS FOURNISSEUR;
CREATE DATABASE IF NOT EXISTS FOURNISSEUR(
    id INT(11) PRIMARY KEY,
    nom VARCHAR(25)
);



DROP DATABASE IF EXISTS BON;
CREATE DATABASE IF NOT EXISTS BON(
    id INT(11) PRIMARY KEY,
    numero INT(11),
    date_cmde DATETIME,
    delai INT(11),
    id_fou INT(11)
);



DROP DATABASE IF EXISTS COMPO;
CREATE DATABASE IF NOT EXISTS COMPO(
    id INT(11) PRIMARY KEY,
    id_art INT(11),
    id_bon INT(11),
    qte INT(11)
);

ALTER TABLE ARTICLE ADD CONSTRAINT FOREIGN KEY(id_fou) REFERENCES FOURNISSEUR(id);
ALTER TABLE BON ADD CONSTRAINT FOREIGN KEY(id_fou) REFERENCES FOURNISSEUR(id);
ALTER TABLE COMPO ADD CONSTRAINT FOREIGN KEY(id_art) REFERENCES ARTICLE(id);
ALTER TABLE COMPO ADD CONSTRAINT FOREIGN KEY(id_bon) REFERENCES BON(id);